# Generated by Django 3.1.1 on 2020-10-01 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournament', '0002_auto_20200926_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Team Name')),
                ('runs', models.IntegerField(default=0, verbose_name='Total Runs Scored by Team')),
                ('fours', models.IntegerField(default=0, verbose_name='Total Fours by Team')),
                ('sixes', models.IntegerField(default=0, verbose_name='Total Sixes by Team')),
                ('wides', models.IntegerField(default=0, verbose_name='Total Wides Thrown by Team')),
                ('noballs', models.IntegerField(default=0, verbose_name='Total No Balls by Team')),
                ('matcheswon', models.IntegerField(default=0, verbose_name='Total Matches Won by Team')),
                ('no_of_players', models.IntegerField(verbose_name='No of Players')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
            ],
        ),
    ]
