# Generated by Django 3.1.1 on 2020-09-26 10:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(2, 'Minimum 2 Characters required')])),
                ('no_of_overs', models.IntegerField()),
                ('no_of_teams', models.IntegerField()),
                ('start_date_time', models.DateTimeField(verbose_name='Start Date nad Time')),
                ('end_date_time', models.DateTimeField(verbose_name='End Date nad Time')),
                ('venue', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
