# Generated by Django 3.1.1 on 2020-09-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='end_date_time',
            field=models.DateTimeField(verbose_name='End Date and Time'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date_time',
            field=models.DateTimeField(verbose_name='Start Date and Time'),
        ),
    ]
