# Generated by Django 3.1.1 on 2020-10-05 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_tournament_no_of_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=128, unique=True, validators=[django.core.validators.MinLengthValidator(2, 'Minimum 2 Characters required')]),
        ),
    ]
