# Generated by Django 3.1.1 on 2020-10-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Player Name')),
                ('runs', models.IntegerField(default=0, verbose_name='Total Runs')),
                ('wickets', models.IntegerField(default=0, verbose_name='Total Wickets Taken')),
                ('fours', models.IntegerField(default=0, verbose_name='Total Fours')),
                ('sixes', models.IntegerField(default=0, verbose_name='Total sixes')),
                ('noballs', models.IntegerField(default=0, verbose_name='No Balls')),
                ('wides', models.IntegerField(default=0, verbose_name='Wides')),
                ('runsgiven', models.IntegerField(default=0, verbose_name='Runs Given')),
            ],
        ),
    ]
